# Generated by Django 5.2.17 on 2026-08-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('pk', models.CompositePrimaryKey('stock', 'stock_date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('stock_date', models.CharField(db_column='STOCK_DATE', max_length=8)),
                ('now_price', models.DecimalField(blank=True, db_column='NOW_PRICE', decimal_places=0, max_digits=18, null=True)),
                ('trade_qty', models.IntegerField(blank=True, db_column='TRADE_QTY', null=True)),
                ('trade_daegum', models.DecimalField(blank=True, db_column='TRADE_DAEGUM', decimal_places=0, max_digits=14, null=True)),
                ('start_price', models.DecimalField(blank=True, db_column='START_PRICE', decimal_places=0, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, db_column='HIGH_PRICE', decimal_places=0, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, db_column='LOW_PRICE', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'OPT10081',
                'ordering': ['-stock_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_code', models.CharField(db_column='STOCK_CODE', max_length=6, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(blank=True, db_column='STOCK_NAME', max_length=100, null=True)),
                ('ybjong_code', models.CharField(db_column='YBJONG_CODE', max_length=6)),
                ('first_date', models.CharField(blank=True, db_column='FIRST_DATE', max_length=8, null=True)),
                ('delete_date', models.CharField(blank=True, db_column='DELETE_DATE', max_length=8, null=True)),
                ('market_gb', models.CharField(blank=True, db_column='Market_Gb', max_length=1, null=True)),
                ('buy_price', models.IntegerField(blank=True, db_column='BUY_PRICE', null=True)),
                ('target_price1', models.IntegerField(blank=True, db_column='Target_Price1', null=True)),
                ('target_price2', models.IntegerField(blank=True, db_column='Target_Price2', null=True)),
                ('target_price3', models.IntegerField(blank=True, db_column='Target_Price3', null=True)),
                ('cut_price1', models.IntegerField(blank=True, db_column='Cut_Price1', null=True)),
                ('cut_price2', models.IntegerField(blank=True, db_column='Cut_Price2', null=True)),
                ('cut_price3', models.IntegerField(blank=True, db_column='Cut_Price3', null=True)),
                ('dividend_rate', models.CharField(blank=True, db_column='Dividend_Rate', max_length=5, null=True)),
                ('stock_contents', models.TextField(blank=True, db_column='Stock_Contents', null=True)),
                ('simple_contents', models.CharField(blank=True, db_column='SIMPLE_CONTENTS', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'SCODE',
                'ordering': ['stock_code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisclosureAnalysis',
            fields=[
                ('rcept_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('report_nm', models.CharField(max_length=255)),
                ('rcept_dt', models.CharField(max_length=8)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='disclosure_analyses', to='stocks.stock')),
            ],
            options={
                'ordering': ['-rcept_dt'],
            },
        ),
    ]
